### ISSUE TITLE
Running `make activity` tracebacks

### ISSUE THREAD

**Issue by FrostyX** [FrostyX/fedora-sponsors#18]
We might need to use a different python library.

```
$ python activity.py
... 
Traceback (most recent call last):
  File "/home/jkadlcik/git/fedora-sponsors/activity.py", line 256, in <module>
    main()
  File "/home/jkadlcik/git/fedora-sponsors/activity.py", line 238, in main
    packagers = client.group_members("packager")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fedora/client/fas2.py", line 404, in group_members
    request = self.send_request('/group/dump/%s' %
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fedora/client/baseclient.py", line 365, in send_request
    session_id, data = super(BaseClient, self).send_request(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fedora/client/proxyclient.py", line 439, in send_request
    raise ServerError(
fedora.client.ServerError: ServerError(https://admin.fedoraproject.org/accounts/group/dump/packager, -1, Request timed out after 120.0 seconds)
```

**Comment by gotmax23** [comment]
Yeah, I don't think the old fas2 instance is operational anymore.

**Comment by FrostyX** [comment]
I think we will be able to use something like this as an alternative
https://gist.github.com/FrostyX/47defa18348fbb917e73d7b2e7660ca2

**Comment by FrostyX** [comment]
Let's see if we get any luck here - https://github.com/fedora-infra/fasjson/issues/522
